/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-container-high": "#e2e8f8",
                "on-secondary-fixed-variant": "#004395",
                "surface-variant": "#dce2f3",
                "on-primary": "#ffffff",
                "on-secondary-fixed": "#001a42",
                "primary-container": "#1e3a8a",
                "surface": "#f9f9ff",
                "surface-dim": "#d3daea",
                "on-secondary": "#ffffff",
                "on-error": "#ffffff",
                "inverse-on-surface": "#ebf1ff",
                "on-tertiary-fixed-variant": "#005236",
                "surface-container": "#e7eefe",
                "tertiary-fixed-dim": "#4edea3",
                "on-background": "#151c27",
                "primary-fixed-dim": "#b6c4ff",
                "on-primary-fixed": "#00164e",
                "on-tertiary": "#ffffff",
                "surface-container-low": "#f0f3ff",
                "tertiary": "#00311f",
                "tertiary-fixed": "#6ffbbe",
                "outline-variant": "#c5c5d3",
                "on-tertiary-container": "#27c38a",
                "surface-container-lowest": "#ffffff",
                "background": "#f9f9ff",
                "error-container": "#ffdad6",
                "secondary-container": "#2170e4",
                "on-error-container": "#93000a",
                "on-tertiary-fixed": "#002113",
                "primary-fixed": "#dce1ff",
                "outline": "#757682",
                "surface-tint": "#4059aa",
                "error": "#ba1a1a",
                "primary": "#00236f",
                "surface-container-highest": "#dce2f3",
                "on-surface": "#151c27",
                "inverse-surface": "#2a313d",
                "on-primary-container": "#90a8ff",
                "secondary-fixed-dim": "#adc6ff",
                "secondary-fixed": "#d8e2ff",
                "surface-bright": "#f9f9ff",
                "inverse-primary": "#b6c4ff",
                "on-primary-fixed-variant": "#264191",
                "on-secondary-container": "#fefcff",
                "secondary": "#0058be",
                "on-surface-variant": "#444651",
                "tertiary-container": "#004a31"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "sm": "8px",
                "gutter": "24px",
                "margin-mobile": "16px",
                "base": "4px",
                "md": "16px",
                "lg": "24px",
                "xl": "40px",
                "container-max": "1280px",
                "xs": "4px"
            },
            fontFamily: {
                "headline-md": ["Inter", "sans-serif"],
                "headline-lg-mobile": ["Inter", "sans-serif"],
                "label-sm": ["Inter", "sans-serif"],
                "label-md": ["Inter", "sans-serif"],
                "display-lg": ["Inter", "sans-serif"],
                "headline-lg": ["Inter", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"]
            },
            fontSize: {
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
                "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
                "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
            }
        },
    },
    plugins: [],
}
